### ISSUE TITLE
Dedicated sso.logged-in event for backend authentication as well

### ISSUE THREAD

**Issue by hitsoul11** [BlackbitDigitalCommerce/pimcore-single-sign-on#12]
Hi there,

we are using the bundle to provide single sign for users provided by Auth0.
Since we cannot configure all user properties via bundle config, we would like to react to an SSO login event and manipulate the user (before creation).
Specifically, this involves the “admin” flag and the language of the user.

As we can see, there is already an “sso.logged-in” event for the frontend login. Why not in the backend too?

**Comment by BlackbitDevs** [comment]
Hi @hitsoul11, 

now (from version 1.2.5) the event `sso.logged-in` also gets triggered for backend logins. You can use this to implement your custom user modifications.

Imho it makes sense to map the language field, too, so I will also add a mapping field for this.

**Comment by hitsoul11** [comment]
Thank you @BlackbitDevs for the quick response and implementation of the event for backend logins.
Could you please pass the provider name as an additional event argument. This would be helpful for specific modifications.

**Comment by BlackbitDevs** [comment]
Have added provider name to the event:
> The `sso.logged-in` event gets triggered on successful login. The following event arguments get provided:
> 
> - `user`: The found / created `\Pimcore\Model\User` object
> - `savePimcoreUser`: boolean value to define if the Pimcore user should get saved (default: true)
> - `provider`: The name of the used SSO provider (as configured in Pimcore backend)

Is released as 1.3.1 (because we merged SAML support today as 1.3)

**Comment by hitsoul11** [comment]
Thanks, I've tested the event. Version 1.3.2 is installed. Unfortunately the provider argument is `null`.
Can confirm that initially `/sso/redirect?provider=[providerName]` is requested. 

If you need additional details, please let me know.

![image](https://github.com/user-attachments/assets/96a666e0-77fd-4048-8b8f-049c1595a4b5)

**Comment by BlackbitDevs** [comment]
Could you please try again with `dev-master`?

**Comment by hitsoul11** [comment]
It's now working. Pleaase remember to add the flag `show_backend_login_button` in the config tree.
Got an error: `Undefined array key "show_backend_login_button"` (InjectListener.php Line 71).

![image](https://github.com/user-attachments/assets/9b0286ff-a121-4aee-947f-e04c7519aad6)

**Comment by BlackbitDevs** [comment]
Sorry, have added the config `show_backend_login_button` and released 1.3.4.
