### ISSUE TITLE
Folder for sso users should be configurable

### ISSUE THREAD

**Issue by hitsoul11** [BlackbitDigitalCommerce/pimcore-single-sign-on#4]
The users are currently stored in the folder "sso".
For a better understanding by non-technical customers (we are an agency), it should be possible to change the folder name per provider.

**Comment by BlackbitDevs** [comment]
Good idea! Have changed this in 1.1.4. The authentication provider name now gets used as folder name. Can you give it a try and report if it works for your use-case?
