### ISSUE TITLE
Pimcore 11 compatibility

### ISSUE THREAD

**Issue by brainformance** [BlackbitDigitalCommerce/pimcore-single-sign-on#5]
Is there a plan for pimcore 11 compatibility?

For example, BlackbitSingleSignOnBundle.php needs to declare return types for its methods.

**Comment by BlackbitDevs** [comment]
Yes, we are working on it. Currently cannot say anything when it will be finished but it is currently in progress.

**Comment by betterapp** [comment]
Any update ?

**Comment by BlackbitDevs** [comment]
Sorry for not responding.
Meanwhile the plugin is compatible with Pimcore 11.
