### ISSUE TITLE
In development?

### ISSUE THREAD

**Issue by NiklasBr** [BlackbitDigitalCommerce/pimcore-single-sign-on#6]
Hi! This may be a very odd question, but there is no `src/` directory here. Is it on it's way perhaps?

**Comment by BlackbitDevs** [comment]
The question is not odd. Thanks to it I now recognized that the shop link was missing in the description ;-)
To get the source code of the bundle, you will have to buy it. This repository here contains only the documentation.
Please see https://github.com/BlackbitDigitalCommerce/pimcore-single-sign-on#how-to-get-the-plugin

**Comment by NiklasBr** [comment]
Now it makes much more sense, thanks!
