### ISSUE TITLE
Login events

### ISSUE THREAD

**Issue by Aloh-cgi** [BlackbitDigitalCommerce/pimcore-single-sign-on#9]
I have tried to use the ldap connection but the method to login with ldap use the event 'pimcore.admin.login.credentials' which does not exist on pimcore.
![image](https://github.com/BlackbitDigitalCommerce/pimcore-single-sign-on/assets/172280439/21a12dcf-c1ab-40de-8e33-fa270138c4c3)
![image](https://github.com/BlackbitDigitalCommerce/pimcore-single-sign-on/assets/172280439/ad8d6508-d401-41aa-a27a-9c74e4b3a60b)

**Comment by BlackbitDevs** [comment]
You are right, in Pimcore 11 the event `pimcore.admin.login.credentials` does not exist anymore but the event is named `Pimcore\Bundle\AdminBundle\Event\Login\LoginCredentialsEvent` there (don't know why they add such artificial BC breaks and not even mention them in https://pimcore.com/docs/platform/Pimcore/Installation_and_Upgrade/Upgrade_Notes/#authentication- ...).
Can you try if it works with `dev-master`, @Aloh-cgi ?
Or if you do not have Bitbucket access, please notify me. Then I will send you the zip file.

**Comment by Aloh-cgi** [comment]
Thank you for your answer. I do not have a bitbucket acces and currently using the version 1.2.1 of the bundle with the zip. @BlackbitDevs

**Comment by BlackbitDevs** [comment]
To which email address / company shall I sent the zip to?

PS: Have updated Pimcore upgrade notes in https://github.com/pimcore/pimcore/pull/17146.

**Comment by Aloh-cgi** [comment]
You can send it to Innoval (eric.hinschberger@innoval.com). Thanks

**Comment by Aloh-cgi** [comment]
Hello, do you have any update for me ?

**Comment by BlackbitDevs** [comment]
I have sent you the zip yesterday at 17:28. I try again...

**Comment by Aloh-cgi** [comment]
Got it, thank you. I will tell you if it fix my problem

**Comment by marcoschivoesse** [comment]
Hi, can you also update the bundle for only ldap https://github.com/BlackbitDigitalCommerce/pimcore-ldap-bundle ?
Or send here the update to file

**Comment by BlackbitDevs** [comment]
Problem actually is not resolved yet, Pimcore simply removed the event. We need to wait for https://github.com/pimcore/pimcore/pull/17158 to be accepted - until then LDAP does not work under Pimcore 11...

**Comment by marcoschivoesse** [comment]
Thanks, I understand... we hope in faster merge!
An information: does the authentication with ldap work only when a user exists with the given username? If in pimcore there isn't the user (but only in ldap), will the bundle create the user if not found on pimcore?

**Comment by BlackbitDevs** [comment]
> If in pimcore there isn't the user (but only in ldap), will the bundle create the user if not found on pimcore?

Yes, the Pimcore user will get created.

**Comment by marcoschivoesse** [comment]
But the event "pimcore.admin.login.failed" (where you hang to create the user) is no longer present or am I wrong?

**Comment by BlackbitDevs** [comment]
Actually this check if the user exists should already be also done at `pimcore.admin.login.credentials`. And this is where https://github.com/pimcore/pimcore/pull/17158 comes into play.

**Comment by marcoschivoesse** [comment]
We tried applying the changes manually but that function only works if it has found the user first. Otherwise the password verification will not occur.

**Comment by BlackbitDevs** [comment]
You mean you have patched Pimcore according to https://github.com/pimcore/pimcore/pull/17158 ?

And you say that the LDAP server does not get asked for password verification? This should not be the case for this bundle but it is for https://github.com/BlackbitDigitalCommerce/pimcore-ldap-bundle - this is one of the weaknesses of the free bundle: It always checks first with Pimcore's default mechanism if login is valid and only afterwards requests the LDAP server. The problem was there that the real LDAP password got ssaved in the Pimcore user. This means that there is no way to disable the account from the outside.
The SSO bundle changes this. After the credentials are validated on LDAP server, a random password will get set to the Pimcore user. Thus Pimcore has to request the LDAP server on every login. And this way the control of the login is really on the LDAP side.

**Comment by marcoschivoesse** [comment]
Thank you very much, I proceed to buy the bundle!

**Comment by BlackbitDevs** [comment]
Found an alternative way to support LDAP login: via `custom_authenticators` for the `security_firewall` config.
